[tool.black]
line-length = 88  # Set your preferred line length
target-version = ['py38']  # Set your target Python version
include = '\.pyi?$'
exclude = '''
    /(
        \.git
        | \.hg
        | \.mypy_cache
        | \.tox
        | \.venv
        | _build
        | buck-out
        | build
        | dist
    )/
'''
[tool.ruff]
# General Ruff settings go here, like target Python version.
target-version = "py311"

[tool.ruff.lint]
# Rule selection and ignoring rules goes under the [tool.ruff.lint] section.
select = ["E", "F"]  # Select all E and F rules by default
ignore = ["E402", "E501", "E701"]    # Ignore E402, E501 (line too long), and E701 (multiple statements on one line) specifically.